In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv(
    '../data/processed/german_credit.csv'
)

df.head()

,status_checking_account,duration,credit_history,purpose,credit_amount,savings_account,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,0
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,1
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,0
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,0
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   status_checking_account  1000 non-null   object
 1   duration                 1000 non-null   int64
 2   credit_history           1000 non-null   object
 3   purpose                  1000 non-null   object
 4   credit_amount            1000 non-null   int64
 5   savings_account          1000 non-null   object
 6   employment_duration      1000 non-null   object
 7   installment_rate         1000 non-null   int64
 8   personal_status_sex      1000 non-null   object
 9   other_debtors            1000 non-null   object
 10  present_residence        1000 non-null   int64
 11  property                 1000 non-null   object
 12  age                      1000 non-null   int64
 13  other_installment_plans  1000 non-null   object
 14  housing                  1000 non-null   object
 15  number_credits           1000 non-null   int64
 16  job                      1000 non-null   object
 17  people_liable            1000 non-null   int64
 18  telephone                1000 non-null   object
 19  foreign_worker           1000 non-null   object
 20  risk                     1000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [5]:
df.shape

(1000, 21)

In [6]:
X = df.drop(
    'risk',
    axis=1
)

y = df['risk']

In [7]:
print(X.shape)
print(y.shape)

(1000, 20)
(1000,)

In [8]:
cat_cols = X.select_dtypes(
    include='object'
).columns.tolist()

num_cols = X.select_dtypes(
    include=['int64','float64']
).columns.tolist()

In [9]:
print(cat_cols)
print(num_cols)

['status_checking_account', 'credit_history', 'purpose', 'savings_account', 'employment_duration', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']
['duration', 'credit_amount', 'installment_rate', 'present_residence', 'age', 'number_credits', 'people_liable']

In [10]:
label_encoders = {}

In [11]:
for col in cat_cols:

    le = LabelEncoder()

    X[col] = le.fit_transform(
        X[col]
    )

    label_encoders[col] = le

In [12]:
X.head()

,status_checking_account,duration,credit_history,purpose,credit_amount,savings_account,employment_duration,installment_rate,personal_status_sex,other_debtors,present_residence,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker
0,0,6,4,4,1169,4,4,4,2,0,4,0,67,2,1,2,2,1,1,0
1,1,48,2,4,5951,0,2,2,1,0,2,0,22,2,1,1,2,1,0,0
2,3,12,4,7,2096,0,3,2,2,0,3,0,49,2,1,1,1,2,0,0
3,0,42,2,3,7882,0,3,2,2,2,4,1,45,2,2,1,2,2,0,0
4,0,24,3,0,4870,0,2,3,2,0,4,3,53,2,2,2,2,2,0,0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
print(X_train.shape)
print(X_test.shape)

(800, 20)
(200, 20)

In [15]:
y_train.value_counts(normalize=True)

risk
0    0.7
1    0.3
Name: proportion, dtype: float64

In [16]:
y_test.value_counts(normalize=True)

risk
0    0.7
1    0.3
Name: proportion, dtype: float64

In [17]:
scaler = StandardScaler()

In [18]:
X_train_scaled = X_train.copy()

X_test_scaled = X_test.copy()

In [19]:
X_train_scaled[num_cols] = scaler.fit_transform(
    X_train[num_cols]
)

In [20]:
X_test_scaled[num_cols] = scaler.transform(
    X_test[num_cols]
)

In [21]:
X_train_scaled.head()

,status_checking_account,duration,credit_history,purpose,credit_amount,savings_account,employment_duration,installment_rate,personal_status_sex,other_debtors,present_residence,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker
828,0,1.289592,2,1,1.925766,4,4,0.052281,2,0,1.053413,3,1.057784,2,2,-0.718745,2,-0.436436,0,0
997,3,-0.742595,2,4,-0.892853,0,4,0.942164,2,0,1.053413,2,0.242449,2,1,-0.718745,2,-0.436436,0,0
148,0,1.289592,4,3,0.816433,0,2,0.052281,2,2,-0.747293,1,-0.663479,2,1,1.045047,2,-0.436436,0,0
735,1,1.289592,1,5,0.299568,4,1,0.052281,1,0,-0.747293,3,-0.572886,0,1,-0.718745,0,-0.436436,0,0
130,1,2.305686,2,0,1.982655,4,3,-1.727486,1,0,-0.747293,2,-1.025850,2,1,-0.718745,2,-0.436436,0,0

In [22]:
X_train.to_csv(
    '../data/processed/X_train.csv',
    index=False
)

X_test.to_csv(
    '../data/processed/X_test.csv',
    index=False
)

y_train.to_csv(
    '../data/processed/y_train.csv',
    index=False
)

y_test.to_csv(
    '../data/processed/y_test.csv',
    index=False
)

In [23]:
X_train_scaled.to_csv(
    '../data/processed/X_train_scaled.csv',
    index=False
)

X_test_scaled.to_csv(
    '../data/processed/X_test_scaled.csv',
    index=False
)

In [24]:
label_encoders.keys()

dict_keys(['status_checking_account', 'credit_history', 'purpose', 'savings_account', 'employment_duration', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker'])